### ISSUE TITLE
Missing validation step for ref.null

### ISSUE THREAD

**Issue by wingo** [WebAssembly/reference-types#110]
A colleague noticed that on https://webassembly.github.io/reference-types/core/valid/instructions.html#xref-syntax-instructions-syntax-instr-ref-mathsf-ref-null-t, it doesn't specify that *t* should be a reference type.  Does another part of the document specify this?

**Comment by binji** [comment]
cc @rossberg 

My guess is that this is omitted because it can never actually be a validation failure -- the `t` in `ref.null t` will always be a reference type, because that is required by the text/binary readers: see https://webassembly.github.io/reference-types/core/binary/instructions.html#reference-instructions and https://webassembly.github.io/reference-types/core/text/instructions.html#reference-instructions

**Comment by rossberg** [comment]
More specifically, the abstract syntax makes this a reference type by construction, see:

https://webassembly.github.io/reference-types/core/syntax/instructions.html#syntax-instr-ref

**Comment by wingo** [comment]
OK makes sense.  Thanks for the info!
