### ISSUE TITLE
Multiple tables take 2

### ISSUE THREAD

**Issue by fgmccabe** [WebAssembly/reference-types#33]
Rather than continue down the road of having tables (editorial comment: arguably tables are the ugliest part of wasm) and having multiple tables, together with table.set etc., a more scalable and powerful approach would be to use managed memory.
Specifically, the array type in the MM proposal looks a lot like tables; with the advantages of being part of a holistic approach to memory.
Since we do not have MM at the moment, I would suggest refactoring multiple table so that it would become part of the ultimate MM proposal. (May no be possible of course).

**Comment by rossberg** [comment]
In theory it would be possible to model both tables and memories as special cases of arrays, but in practice they have different implementation strategies. Moreover, it was stated as a requirement by the CG early on that other features, as well as the ability to manage host references, should not become dependent on the GC proposal, so that GC can remain an optional feature.

**Comment by fgmccabe** [comment]
I think that this misses my point. It is not to take a dependency on GC; but rather to ensure that things like types and access APIs are written in such a way that they could be folded in later on.
As for the use case, it may be true that initially tables had a very different use case. But the introduction of multiple tables, together with instructions for managing entries in the tables inevitably makes tables less special purpose and more like general arrays.

**Comment by lars-t-hansen** [comment]
I suspect the ship has sailed for this proposal; the GC feature is a long way off and the reference-types feature continues to provide multiple tables.  @fgmccabe, anything to add or can we close?
