### ISSUE TITLE
Is this the spec that covers being able to work with DOM objects from inside WASM?

### ISSUE THREAD

**Issue by trusktr** [WebAssembly/reference-types#49]
?

**Comment by Pauan** [comment]
Technically yes, though it really applies to *all* JS values (not just the DOM), and it even applies to non-JS values (e.g. in non-JS hosts). References are extremely general.

And even with this proposal you still need JS wrappers in order to actually *do* anything with the DOM.

This is the spec that's *specific* to the DOM:

https://github.com/WebAssembly/webidl-bindings

**Comment by trusktr** [comment]
Ah, thanks!
