### ISSUE TITLE
Tests and spec disagree about call_indirect table specifier

### ISSUE THREAD

**Issue by sbc100** [WebAssembly/reference-types#59]
`test/core/ref_func.wast` seems to think the table comes first, before the sig. e.g: https://github.com/WebAssembly/reference-types/blob/1e05d9bbfa9c5497ac1e95b59c48b3aacd50d88e/test/core/ref_func.wast#L33

```
  (func (export "call-g") (param $x i32) (result i32)                            
    (table.set $t (i32.const 0) (ref.func $g))                                   
    (call_indirect $t (param i32) (result i32) (local.get $x) (i32.const 0))     
  )             
```

Whereas the spec test says it comes after:

```
call_indirect (type $t) $x : [t1* i32] -> [t2*]
iff $t = [t1*] -> [t2*]
and $x : table t'
and t' <: funcref
```

wabt also seems to have implemented the later:  https://github.com/WebAssembly/wabt/blob/a147d92575d386ef45c75a3e492c8ca4d33a3bbc/test/parse/expr/reference-types-call-indirect.txt#L13

I hope the tests, rather than the spec, can be updated since add an extra optional parameter seems to be much simpler to implement in the parser.

**Comment by rossberg** [comment]
The test is correct, and consistent with the text format in the [draft spec](https://webassembly.github.io/reference-types/core/text/instructions.html#control-instructions). I'll fix the overview.

Having the table index first is way more consistent with the other instructions, where the index of the main subject always is first, and never after a non-trivial thing like a typeuse.

IME, having the index first also is significantly easier to implement, because there are so many ways to expand a typeuse into an arbitrary number of items.

**Comment by sbc100** [comment]
Ok that makes sense.  And just to be clear the table specifier is required (not optional) n the text format after this proposal?

**Comment by rossberg** [comment]
No, it's optional for backwards compat. Same in other places and with memory indices in the multi-mem proposal.

**Comment by sbc100** [comment]
Is that optional-ness reflected in the draft spec?  I didn't see anything when reading it.

I think it was the fact that it was optional that was causing difficulties for the wabt parser but I'll have another go now.

**Comment by rossberg** [comment]
Yes, see Abbreviations below.

**Comment by sbc100** [comment]
Great, sorry I didn't spot that.  I will update wabt, which currently implement the "table as last arg" approach.

**Comment by rossberg** [comment]
In case, just steal the grammar from the reference interpreter. :)
