### ISSUE TITLE
[test] Bulk instructions with multiple tables

### ISSUE THREAD

**Issue by rossberg** [WebAssembly/reference-types#74]
The bulk proposal adds new table instructions, while this proposal adds multiple tables. The intersection of the two proposals has been implemented and spec'ced here after rebasing this on bulk, but we also need to extend the existing tests for those bulk instructions. In particular, test `table.copy` between different tables is a somewhat interesting case.

The respective tests are generated by scripts. @lars-t-hansen, would you or somebody else familiar with those scripts be willing to extend them?

**Comment by lars-t-hansen** [comment]
@rossberg, Yeah, I can look into that, we've probably updated them similarly on our side already.  I'll ping you if I have further questions.

**Comment by fitzgen** [comment]
Just noticed that while the text format has `x` and `y` table indices for `table.copy`, the binary encoding still only has `0x00 0x00` placeholders. (Aside: maybe we should use `s` and `d` for "source" and "destination" instead of `x` and `y`? Or something else more descriptive.)

Additionally, the validation spec text does not take table indices into account, only mentions a hard-coded `table[0]`. (The execution spec text, on the other hand, does seem to take multiple tables into account).

Should I file new issue(s) for the binary encoding and validation bits, or is this issue appropriate for tracking these multi-table / non-zero table uses of `table.copy`?

**Comment by rossberg** [comment]
Ah, thanks! Yeah, I think having a single issue is sufficient.

**Comment by rossberg** [comment]
@fitzgen, fixed by #80, thanks!

**Comment by lars-t-hansen** [comment]
There also seem to be no call_indirect tests through tables other than the default table?

**Comment by rossberg** [comment]
@lars-t-hansen, good point. See #83.
